---
title: "ML_original_data"
author: "Penca Matei"
date: "12/23/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Packages & Data

```{r warning = FALSE, message = FALSE}
library(readr)
library(performance)
library(gmodels)
library(caret)
library(tidyverse)
library(tree)
library(randomForest)
```

### Loading and setting up the data

```{r warning = FALSE, message = FALSE}

# Load data into the environment and creates partition for 50-50 validation

german_credit <- read_csv("data/german_credit.csv")


Train50 <- read_csv("data/Training50.csv")


Test50 <- read_csv("data/Test50.csv")


attach(Train50)


```

### Logistic regression model with 50:50 Cross-validation

```{r warning = FALSE, message = FALSE}

LogisticModel50final <- glm(Creditability ~ Account.Balance +
                              Payment.Status.of.Previous.Credit + Purpose + 
                              Length.of.current.employment + 
                              Sex...Marital.Status, family=binomial, 
                            data = Train50)

fit50 <- fitted.values(LogisticModel50final)

Threshold50 <- rep(0,500)

for (i in 1:500)
  if(fit50[i] >= 0.5) Threshold50[i] <- 1
CrossTable(Train50$Creditability, Threshold50, digits=1, prop.r=F, prop.t=F, 
           prop.chisq=F, chisq=F, data=Train50)


for (i in 1:500) {
  if (Threshold50[i] == '1') {
    Threshold50[i] <- 'Creditable'
  }
  
  if (Threshold50[i] == '0') {
    Threshold50[i] <- 'Non-Creditable'
  } 
}

for (i in 1:500) {
  if (Test50$Creditability[i] == '0') {
    Test50$Creditability[i] <- 'Non-Creditable'
  } 
  
  if (Test50$Creditability[i] == '1') {
    Test50$Creditability[i] <- 'Creditable'
  } 
}
```


### Confusion matrix for GLM

```{r warning = FALSE, message = FALSE}
confusion <- confusionMatrix(data = factor(Threshold50),
                             reference = factor(Test50$Creditability))
confusion
```

### Supervised Tree based method

```{r warning = FALSE, message = FALSE}

# Reload the clean test data set into memory
Test50 <- read_csv("data/Test50.csv")

Train50_tree <- tree(as.factor(Creditability) ~ Account.Balance+
                       Duration.of.Credit..month.+
                       Payment.Status.of.Previous.Credit+Purpose+Credit.Amount+
                       Value.Savings.Stocks+
                       Length.of.current.employment+Instalment.per.cent+
                       Sex...Marital.Status+Guarantors+
                       Duration.in.Current.address+
                       Most.valuable.available.asset+Age..years.+
                       Concurrent.Credits+Type.of.apartment+
                       No.of.Credits.at.this.Bank+Occupation+No.of.dependents+
                       Telephone, data=Train50, method="class")

summary(Train50_tree)

# Tree visual representation
plot(Train50_tree)
text(Train50_tree, pretty=0,cex=0.6)

# Simple confusion matrix without pruning
Test50_pred <- predict(Train50_tree, Test50, type="class")
table(Test50_pred, Test50$Creditability)

Train50_prune8 <- prune.misclass(Train50_tree, best=8)
Test50_prune8_pred <- predict(Train50_prune8, Test50, type="class")



```

### Confusion matrix for supervised trees (with pruning)

```{r warning = FALSE, message = FALSE}
confusionTree <- confusionMatrix(data = factor(Test50_prune8_pred),
                                 reference = factor(Test50$Creditability))
confusionTree
```


### Unsupervised Random Forest based method

```{r warning = FALSE, message = FALSE}

rf50 <- randomForest(as.factor(Creditability) ~., data = Train50, ntree=200, importance=T, proximity=T)
plot(rf50, main="")
rf50

Test50_rf_pred <- predict(rf50, Test50, type="class")


```

### Confusion matrix for unsupervised random forest

```{r warning = FALSE, message = FALSE}

confusionForest <- confusionMatrix(data = factor(Test50_rf_pred),
                                   reference = factor(Test50$Creditability))
confusionForest
```
